input.onButtonPressed(Button.A, function () {
    basic.pause(3600000)
    basic.showString("One Hour")
    basic.pause(3600000)
    basic.showString("Three Hour")
    basic.pause(3600000)
    basic.showString("Four Hour")
    basic.pause(3600000)
    basic.showString("Five Hour")
    basic.pause(3600000)
    basic.showString("Six Hour")
    basic.pause(3600000)
    basic.showString("Seven Hour")
    basic.pause(3600000)
    basic.showString("Eight Hour")
    basic.pause(3600000)
    basic.showString("Nine Hour")
    basic.pause(3600000)
    basic.showString("Ten Hour")
    basic.pause(3600000)
    basic.showString("Eleven Hour")
    basic.pause(3600000)
    basic.showString("Twelve Hour")
    basic.pause(5000)
    basic.showString("Half A Day")
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("C5 D E C B G C C ", 120)
})
input.onGesture(Gesture.Shake, function () {
    music.playMelody("C5 B D C F C5 E A ", 120)
})
basic.forever(function () {
    basic.showNumber(input.runningTime())
})
